### ISSUE TITLE
Проверить гиперы и Зоны. 

### ISSUE THREAD

**Issue by Kender013** [Dark-raven-lab/SpaceProject#10]
Проверить настройки, сделать нубскую бесплатную зону на 100кВт..

**Comment by Dark-raven-lab** [comment]
Гиперы уже делали https://github.com/Dark-raven-lab/SpaceProject/issues/2

Зону залил https://github.com/Dark-raven-lab/SpaceProject/commit/ee0948575a34bd306051017dc6346188f648b54e
