### ISSUE TITLE
Накидать кокпиты

### ISSUE THREAD

**Issue by Dark-raven-lab** [Dark-raven-lab/SpaceProject#6]
Нужно проверить работу каждого и если ок, то докинуть в общий мод

Например
https://steamcommunity.com/sharedfiles/filedetails/?id=389589518
https://steamcommunity.com/sharedfiles/filedetails/?id=1379837654
https://steamcommunity.com/sharedfiles/filedetails/?id=2486269122

При необходимости написать автору и получить разрешение на переиспользование с указанием оригинального автора.

**Comment by Kender013** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=389589518 - Да. можно
https://steamcommunity.com/sharedfiles/filedetails/?id=1379837654 - Да. берем если не найду похожий но с обзором вперед
https://steamcommunity.com/sharedfiles/filedetails/?id=2486269122 - нет. это просто окна а не кокпит.. занимают внутреннее пространство и не дают возможность внутри себя ставить. дублируют существующее, чисто дизайн.
https://steamcommunity.com/sharedfiles/filedetails/?id=2328844782 - Да. Интересный кокпит для ровера
https://steamcommunity.com/sharedfiles/filedetails/?id=303417641 - Да. Сферический с респ капсулы 
https://steamcommunity.com/sharedfiles/filedetails/?id=2890765107 - Да. Набор Шароидов. Автор не дает переразмещать. Использовать как есть.

На данном момент предлагаю их "подключать" потом как все отпишутся - можно интегрировать.
